### ISSUE TITLE
USB "set options" error

### ISSUE THREAD

**Issue by phil-pilgrim** [parallaxinc/BlocklyPropLauncher#101]
I get the below-illustrated error quite often. It happens with a Propeller Activity Board whenever I power it off and back on -- once in a while at other times, too. The USB is still connected and recognized by Solo and my PC (Win 7). I have to unplug the USB connector, wait for the port to disappear from the Solo menu, plug it back in again, and wait some more for it to reappear. I do not have a similar issue with the Propeller Tool, for example.

![USB error](https://user-images.githubusercontent.com/61169172/75479262-1143c380-5954-11ea-8c8c-16cded3ef7a7.png)

**Comment by PropGit** [comment]
Version 1.0.1 will be release 5/22/2020.  It may have fixed this issue.  Please verify.

**Comment by phil-pilgrim** [comment]
Latest release on Parallax website is still 0.11.2.

**Comment by zfi** [comment]
The 1.0.1 installers for Windows and MacOS have been deployed to Solo and the Parallax web site.

**Comment by PropGit** [comment]
The Parallax website has been updated this morning as well.

**Comment by phil-pilgrim** [comment]
I'm sorry to report, but I still get the same error. Moreover, even when it "works," I sometimes have to wait seven or eight seconds after I see **Download...** for the actual downloading to begin. Finally, downloading _never_ works after the first time the USB cable is connected. This is what I see:

![cannot_open](https://user-images.githubusercontent.com/61169172/83052389-17eddf80-a004-11ea-8412-dc7964e02ecb.png)

The second attempt works, though, unless I get the **Cannot set port options** error.

Just to verify:

![launcher_1_0_1](https://user-images.githubusercontent.com/61169172/83052909-d0b41e80-a004-11ea-8fbf-37cb61eafc2a.png)

Again, running Chrome on Win7.

**Comment by zfi** [comment]
@phil-pilgrim: Are you running this on solo.parallax.com or blockly.parallax.com? We have tested both sites extensively and have not seen the issue you are noting after the 1.0.1 Launcher release.

**Comment by phil-pilgrim** [comment]
https://phil-pilgrim.github.io/solo/blocklyc.html

**Comment by zfi** [comment]
Can you try this on solo.parallax.com and see if you have better results?

**Comment by PropGit** [comment]
I just did 25 successful downloads from your site.  

This may be a hardware/timing difference I can't duplicate.  

Please click on the Launcher's gear icon and check Verbose Logging, then do a download and past a screenshot.  Here's mine from a download via your Solo site:

![image](https://user-images.githubusercontent.com/1266318/83056156-c3e5f980-a009-11ea-8841-527d7746f8a3.png)

**Comment by phil-pilgrim** [comment]
On **solo.parallax.com** now:

1. With the USB cable plugged in, and with the Activity Board power off, I don't get any error; it just hangs after **Download...**

2. After unplugging the USB cable, turning on the AB, then plugging in the USB cable, and waiting for the port number to appear in the drop-down menu, a download hangs for awhile before I get the **Cannot find port** error.

3. Second time I got a successful download, but only after waiting a minute or more for it to begin.

4. Third and subsequent times, same thing. During the wait, there is no activity indicated by the AB's USB LEDs. Also, COM101 remains displayed in the drop-down menu.

Okay, log stuff to follow...

**Comment by PropGit** [comment]
The verbose logging starting before you plug in the USB port may help us too.  I've seen some systems make the port available, but then preempt more CPU time for any software that tries to open it for a while (presumably because the kernel is still configuring something).  Along that note, if you attempt a download with Propeller Tool right after plugging the USB cable back in, does it download immediately?

**Comment by phil-pilgrim** [comment]
With AB off and USB plugged in:

![log_with_AB_off](https://user-images.githubusercontent.com/61169172/83056908-078d3300-a00b-11ea-8577-79175829eda4.png)

After turning on AB with USB still plugged in:

![log_first_AB_on](https://user-images.githubusercontent.com/61169172/83057155-62268f00-a00b-11ea-9187-b61f07ef4f01.png)

Second attempt with AB still on:

![log_second_AB_on](https://user-images.githubusercontent.com/61169172/83057431-bcbfeb00-a00b-11ea-83e0-2a4141116fd7.png)

Unplug USB, then plug it back in:

![log_unplug_replug](https://user-images.githubusercontent.com/61169172/83057663-17594700-a00c-11ea-89ec-0bfc142f4d73.png)

I got no successful downloads during this test sequence.

**Comment by phil-pilgrim** [comment]
Oops! Forgot to clip images. Hang on ...

**Comment by phil-pilgrim** [comment]
With Prop Tool, download succeeds immediately , without delay, after plugging in USB cable.

**Comment by PropGit** [comment]
Thanks.

Let's see what FTDI driver version is attached to that port.  

- Plug the AB in via USB
- Open up Windows Device Manager
- Expand Ports (COM & LPT)
- Double-click the "USB Serial Port (COM101)" item
- Select the Driver tab
- Screenshot.

May need to check Programs and Features also, near the bottom, for Windows Driver Package - FTDI CDM... and ...Parallax Inc CDM...  version(s).

**Comment by PropGit** [comment]
> With Prop Tool, download succeeds immediately , without delay, after plugging in USB cable.

That's interesting.  I'm out of ideas at the moment.  I'll check back when something occurs to me or if you have an update.  Thank you very much for trying this out.

**Comment by phil-pilgrim** [comment]
![com101_properties](https://user-images.githubusercontent.com/61169172/83059665-1d9cf280-a00f-11ea-9550-f7ff97089f89.png)

**Comment by PropGit** [comment]
That version should be fine, though in my case I'm using 2.12.28.  We haven't wrapped that one yet for customers because we haven't known of any problems really requiring it.  FTDI hasn't been very clear about what changes were included since then.  You can get their executable installer here if you want to try it:  https://www.ftdichip.com/Drivers/CDM/CDM21228_Setup.zip

However, before you do such a thing, please try the attached version of BlocklyProp Launcher (v1.0.2).  I've added a log of a chrome error (if there is one) that should appear before the "Can not set port... options" error you're getting.

[BPL_v1.0.2.zip](https://github.com/parallaxinc/BlocklyPropLauncher/files/4691378/BPL_v1.0.2.zip)

* Close your current BP Launcher
* Extract the archive into a new (empty) folder
* Navigate Chrome to chrome://extensions
* Turn on Developer Mode (upper-right)
* Click Load Unpacked and point it at the folder where you extracted the archive
* Open a new tab and click the Apps button or navigate to chrome://apps and find the BP Launcher and run it

Make sure it shows v1.0.2 at the bottom of it's window when it runs.

Try the same tests you did before that resulted in the "Can not set port... options" message, then take a screenshot of the log view in BlocklyProp Launcher.

**Comment by phil-pilgrim** [comment]
Done:

![log_1_0_2](https://user-images.githubusercontent.com/61169172/83075354-8d6ba700-a028-11ea-8f4d-7fe0818931bf.png)

**Comment by PropGit** [comment]
Thanks.  That proves that there's no error condition I'm missing at that point in the code, but it doesn't clearly lead me to a solution... I still don't know why it fails on your computer.

Do you have another Win7 computer you can try this on?

**Comment by phil-pilgrim** [comment]
> Do you have another Win7 computer you can try this on?

Unfortunately not.

**Comment by phil-pilgrim** [comment]
Just an update: I installed the 2.12.28 FTDI driver, but nothing under BPLauncher 1.0.1 has changed.

BTW, before rerunning the tests, I was getting a persistent message that Solo could not find the launcher. Reinstalling the launcher fixed that problem.

**Comment by PropGit** [comment]
Thanks @phil-pilgrim.  I have another idea; perhaps something in the stream is causing a communication error, such as an undetected stop bit.  The serial API used in the app tends to "pause" the port when this happens and Launcher has to unpause it.  When the port is "paused" there's not much that can be done with the port through the API.  I think it's already unpausing, but perhaps it needs to unpause at a different point in the stream.

If your project is transmitting any data during runtime, this is a possibility.  It should be reasonably detectable by starting fresh (in a state where the download is likely to be successful) switching to another project that perhaps just blinks LEDs or actuates a motor instead of sending serial data over the USB connection, then attempt multiple downloads of that non-serial project (and others like it) to see if the "set options" error happens any more.  Then, if no "set options" error, download your current (serial communicating) project multiple times to see if there are any errors.

**Comment by phil-pilgrim** [comment]
> If your project is transmitting any data during runtime, this is a possibility.

It's not transmitting anything.

I know this was an occasional issue with PropTool, but I haven't seen it in years. Jeff Martin might be your best resource to get this sorted. In any event, asserting DTR should put an end to any transmission from the Prop, unless you wait too long, and the EEPROM program starts up again.

Did I read something somewhere about uploading a bootloader ahead of the actual program? If so, why not just use the the serial protocol built in to the Prop's ROM loader?

**Comment by PropGit** [comment]
Sorry for missing this response.

> I know this was an occasional issue with PropTool, but I haven't seen it in years. Jeff Martin might be your best resource to get this sorted.

PropGit = Jeff Martin  :-)

Yes, I remember the occasional issue with PropTool.  Still chasing this one you've found in BP Launcher.  Another customer has same issue now and noted some additional possible clues, which brought me back to this thread.

> asserting DTR should put an end to any transmission from the Prop, unless you wait too long, and the EEPROM program starts up again.

Right, asserting DTR will put an end to transmission, but the can't set options error is because the OS is refusing to control DTR at that moment... also, there could be serial data received (but not exposed by the kernel to the app layer yet) prior to a successful DTR.  Makes like fun.

> Did I read something somewhere about uploading a bootloader ahead of the actual program? If so, why not just use the the serial protocol built in to the Prop's ROM loader?

Yes, to achieve a much faster download (and one capable of surviving many unexpected delays in the serial stream that are imposed by new OS releases, computer hardware issues, and/or network traffic (if programming over IP; wired or wireless), I wrote a very small boot loader that can communicate at many baud rates and is fine waiting up to 2.5 seconds or so between packets.  We use the ROM built-in boot loader to load this small fast boot loader which switches to using the on-board crystal as it's time base, then the host system cranks up the baud rate to 921600 and delivers the user application in a packetized fashion; it's very swift.

The problem we're seeing in this issue isn't directly related to the fast boot loader, but rather seems related to the way the Chrome engine interfaces to the Windows serial API.  That's my theory, anyway.
